# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

defaults: &defaults
  working_directory: ~/project

  docker:
    - image: continuumio/miniconda3

commands:
  test:
    description: "Run Tests"

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            apt-get --yes update
            apt-get --yes install build-essential
            conda config --set always_yes yes --set changeps1 no

      - run:
          name: Create Conda Environment
          command: |
            conda create -v --quiet --prefix test-environment --show-channel-urls "python=3" scipy "blas=*=openblas"

      - attach_workspace:
          at: ~/project

      - run:
          name: Output Environment
          command: |
            conda env export --prefix ~/project/test-environment

      - run:
          name: Run Tests
          no_output_timeout: 30m
          command: |
            source activate ~/project/test-environment
            OMP_NUM_THREADS=1 python timelu.py

jobs:
  test-scipy:
    <<: *defaults

    steps:
      - test


workflows:
  version: 2

  test:
    jobs:
      - test-scipy
